# Setup
title: Leonardo Ripple
description: Currently persuing bachelors degree in Huazhong University of Science and Technology
url: https://leonardoripple127.github.io/Leonardo-Ripple.github.io
avatar: /my_profile.jpg
paginate: 10
permalink: pretty
cover_image: /new_background.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Leonardo Ripple
  card: summary
logo: logo.png
social:
  name: Leonardo Ripple
  links:
    - https://github.com/LeonardoRipple127
    
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Leonardo Ripple
  url: https://github.com/LeonardoRipple127/
  email: leonardoripple0128@gmail.com
